basic/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.home, name='home'),
    path('meal/', views.meal, name='meal'),
]

codeboard/urls.py
from django.urls import path
from . import views

app_name = 'codeboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.create_comments, name='create_comments'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.delete_comments, name='delete_comments'),
    path('<int:pk>/like/', views.like, name='like'),
]

normalboard/urls.py
from django.urls import path
from . import views

app_name = 'normalboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.create_comments, name='create_comments'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.delete_comments, name='delete_comments'),
    path('<int:pk>/like/', views.like, name='like'),
]

project304/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic.urls')),
    path('', include('accounts.urls')),
    path('community/', include('normalboard.urls')),
    path('martor/', include('martor.urls')),
    path('code/', include('codeboard.urls')),
    path('question/', include('questionboard.urls')),
]

questionboard/urls.py
from django.urls import path
from . import views

app_name = 'questionboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.create_comments, name='create_comments'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.delete_comments, name='delete_comments'),
    path('<int:pk>/like/', views.like, name='like'),
]

project304/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}
  {% endblock %}
  <link rel="stylesheet" href="{% static 'base.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicons.ico' %}">
  {% block css %}
  {% endblock %}
</head>

<body>

  {% if user.is_authenticated %}

  <nav class="topnav">
    <a href="/home/" class="logo"><img src="{% static 'logo3.png' %}" alt="" class="logo"></a>
    <ul class="boardlists">
      <li><a href="{% url 'normalboard:index' %}" class="boardlist">일반 게시판</a></li>
      <li><a href="{% url 'codeboard:index' %}" class="boardlist">코드공유 게시판</a></li>
      <li><a href="{% url 'questionboard:index' %}" class="boardlist">질문 게시판</a></li>
      <li><a href="{% url 'meal' %}" class="boardlist">식단표</a></li>
    </ul>
    <div class="profile-area">
      <div class="profile-set">
        <div id="clickbox1">
          <div class="user-box">
            <span>{{ user.student.number }}</span>
            <span><em>{{ user.last_name }}{{ user.first_name }}</em>님</span>
          </div>
        </div>
      </div>
      <div id="profile-layer">
        <div class="layer-inner">
          <div id="clickbox2">
            <div class="user-box">
              <span>{{ user.student.number }}</span>
              <span><em>{{ user.last_name }}{{ user.first_name }}</em>님</span>
            </div>
          </div>
          <form action="{% url 'logout' %}" id="logout" method="POST">
            {% csrf_token %}
            <a href="{% url 'change_password' %}" class="change-pw">
              <i class="icon-change-pw"></i>
              <span>비밀번호 변경</span>
            </a>
            <button type="submit">
              <i class="icon-logout"></i>
              <span>로그아웃</span>
            </button>
          </form>
        </div>
      </div>
      <div id="hamburger">
        <div class="hamburger-icon"></div>
      </div>
    </div>
    <div class="links">
      <a href="http://edu.ssafy.com/" class="link edu"><span>EDU<br>SSAFY</span></a>
      <a href="https://lab.ssafy.com/" class="link lab"><span>LAB<br>SSAFY</span></a>
      <a href="http://job.ssafy.com/" class="link job"><span>JOB<br>SSAFY</span></a>
    </div>
  </nav>
  <div id="dropdown-mobile">
    <a href="{% url 'normalboard:index' %}" class="dropdown-menu">일반 게시판</a>
    <a href="{% url 'codeboard:index' %}" class="dropdown-menu">코드공유 게시판</a>
    <a href="{% url 'questionboard:index' %}" class="dropdown-menu">질문 게시판</a>
    <a href="{% url 'meal' %}" class="dropdown-menu">식단표</a>
    <a href="http://edu.ssafy.com/" class="dropdown-menu">EDU SSAFY</a>
    <a href="https://lab.ssafy.com/" class="dropdown-menu">LAB SSAFY</a>
    <a href="http://job.ssafy.com/" class="dropdown-menu">JOB SSAFY</a>
  </div>

  <div class="container">
    {% if messages %}
    {% for message in messages %}
    {% if message.tags %}
    <script>
      alert('{{ message }}')
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% block contents %}
    {% endblock %}
  </div>
  {% else %}
  <div class="container">
    <h1 class="login-required">로그인이 필요한 페이지입니다.</h1>
    <form action="{% url 'login' %}" class="loginlink-form">
      <button class="loginlink-btn">로그인 하러가기</button>
    </form>
  </div>
  {% endif %}

</body>
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
<script src="{% static 'base.js' %}"></script>
<script src="https://kit.fontawesome.com/f439b3e130.js" crossorigin="anonymous"></script>
{% block script %}
{% endblock %}

</html>