basic/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.home, name='home'),
    path('meal/', views.meal, name='meal'),
]

normalboard/urls.py
from django.urls import path
from . import views

app_name = 'normalboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.create_comments, name='create_comments'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.delete_comments, name='delete_comments'),
    path('<int:pk>/like/', views.like, name='like'),
]

project304/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic.urls')),
    path('', include('accounts.urls')),
    path('community/', include('normalboard.urls')),
    path('martor/', include('martor.urls')),
    path('code/', include('codeboard.urls')),
    path('question/', include('questionboard.urls')),
]

normalboard/models.py
from django.db import models
from martor.models import MartorField
from django.conf import settings

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=20)
    password = models.CharField(max_length=8)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = MartorField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hit = models.IntegerField(default=0)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

normalboard/forms.py
from django import forms
from .models import Post, Comment
from martor.fields import MartorFormField

class PostForm(forms.ModelForm):
    title = forms.CharField(
        label='글 제목',
        label_suffix='',
        widget=forms.TextInput(
            attrs = {
                'placeholder':'글 제목을 입력하세요.',
                'class': 'form',
            }
        )
    )
    content = MartorFormField()
    password = forms.CharField(
        label='글 비밀번호 설정',
        label_suffix='',
        widget=forms.PasswordInput(
            attrs = {
                'class': 'form password-form',
            }
        )
    )
    class Meta:
        model = Post
        fields = ['title', 'content', 'password']

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
        label_suffix='',
        widget=forms.TextInput(
            attrs = {
                'placeholder': '댓글을 입력하세요.',
                'class': 'commentinput input-responsive',
            }
        )
    )
    class Meta:
        model = Comment
        fields = ['content']

normalboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from datetime import datetime
from django.db.models import F

# Create your views here.
@login_required
def index(request):
    posts = Post.objects.order_by('-pk')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'normalboard/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, '글 작성이 완료되었습니다.')
            return redirect('normalboard:detail', post.pk)
        messages.warning(request, '글 제목은 20자 이내, 비밀번호는 8자 이내입니다.')
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'normalboard/form.html', context)

@login_required
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    commentform = CommentForm()
    comments = post.comment_set.all()
    if request.session.get('_auth_user_id'):
        cookie_name = f'hit:{request.session["_auth_user_id"]}'
    else:
        cookie_name = 'hit'
    tomorrow = datetime.replace(datetime.now(), hour=23, minute=59, second=0)
    expires = datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S GMT")
    context = {
        'post': post,
        'commentform': commentform,
        'comments': comments,
    }
    response = render(request, 'normalboard/detail.html', context)
    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(post.id) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{post.id}', expires=expires)
            post.hit = F('hit') + 1
            post.save()
    else:
        response.set_cookie(cookie_name, post.id, expires=expires)
        post.hit = F('hit') + 1
        post.save()
    return response

@login_required
def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    data = {
        'title': post.title,
        'content': post.content,
    }
    form = PostForm(data)
    context = {
        'form': form,
        'post': post,
    }
    if request.POST.get('password') != post.password:
        messages.error(request, '글 비밀번호가 일치하지 않습니다.')
        return redirect('normalboard:detail', post.pk)
    return render(request, 'normalboard/form.html', context)

@login_required
@require_POST
def update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    data = {
        'title': post.title,
        'content': post.content,
    }
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            if form.cleaned_data.get('password') == post.password:
                post = form.save()
                messages.success(request, '글 수정이 완료되었습니다.')
                return redirect('normalboard:detail', post.pk)
            else:
                messages.error(request, '글 비밀번호가 일치하지 않습니다.')
        else:
            messages.error(request, '제출 양식이 올바르지 않습니다.')
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'normalboard/form.html', context)

@login_required
def delete(request, pk): 
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        if request.POST.get('password') == post.password:
            post.delete()
            messages.success(request, '글 삭제가 완료되었습니다.')
            return redirect('normalboard:index')
        else:
            messages.error(request, '글 비밀번호가 일치하지 않습니다.')
            return redirect('normalboard:detail', post.pk)
    context = {
        'post': post,
    }
    return render(request, 'normalboard/detail.html', context)

@login_required
@require_POST
def create_comments(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = post
        form.save()
        messages.success(request, '댓글이 등록되었습니다.')
    else:
        messages.error(request, '내용을 입력해 주십시오.')
    return redirect('normalboard:detail', pk)

@login_required
@require_POST
def delete_comments(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    messages.success(request, '댓글이 삭제되었습니다.')
    return redirect('normalboard:detail', pk)

@login_required
def search(request):
    keyword = request.GET.get('query')
    posts = Post.objects.filter(title__contains=keyword).order_by('-pk')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'normalboard/index.html', context)

@login_required
def like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.like_users.filter(id=request.user.pk).exists():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    return redirect('normalboard:detail', pk)

normalboard/templates/normalboard/detail.html
{% extends 'base.html' %}
{% load static %}
{% load martortags %}

{% block title %}
<title>{{ post.title }} - 일반 게시판</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'monokai-sublime.css' %}">
<link rel="stylesheet" href="{% static 'detail.css' %}">
{% endblock %}

{% block contents %}

<h2 class="detailtitle">{{ post.title }}</h2>
<div class="postdata">
  <h5 class="authordata">{{ post.author.last_name }}{{ post.author.first_name }}</h5>
  <div class="seperate"></div>
  <h5 class="datedata">{{ post.created_at|date:'Y.m.d H:i' }}</h5>
</div>
<hr>
<div class="content">
  {{ post.content|safe_markdown }}
</div>
<hr>

<p class="commentnum-infobox">
  총 <span class="commentnum-info">{{ post.comment_set.all|length }}</span>건의 댓글이 있습니다.
  {% if request.user in post.like_users.all %}
  <a href="{% url 'normalboard:like' post.pk %}" class="like"><i class="fas fa-heart"></i>  {{ post.like_users.all|length }}</a>
  {% else %}
  <a href="{% url 'normalboard:like' post.pk %}" class="like"><i class="far fa-heart"></i>  {{ post.like_users.all|length }}</a>
  {% endif %}
</p>
<hr>

<h3 class="comment-write">댓글쓰기</h3>
<form action="{% url 'normalboard:create_comments' post.pk %}" method="POST" class="commentform">
  {% csrf_token %}
  {{ commentform }}
  <button class="commentbtn btn-responsive comment-create">등록</button>
</form>
<hr>

<div class="comments">
  {% for comment in comments %}
  <div class="commentbox">
    <div class="comment-metadata">
    <div class="comment-profile">
      <span class="comment-username">{{ comment.user.last_name }}{{ comment.user.first_name }}</span>
      <div class="seperate"></div>
      <h5 class="datedata comment-date">{{ comment.created_at|date:'Y.m.d H:i' }}</h5>
    </div>
    {% if comment.user == request.user %}
    <form action="{% url 'normalboard:delete_comments' post.pk comment.pk %}" method="POST">
      {% csrf_token %}
      <button class="commentbtn btn-responsive comment-delete">삭제</button>
    </form>
    {% endif %}
  </div>
    <p>{{ comment.content }}</p>
  </div>
  <hr>
  {% endfor %}
</div>





{% if request.user == post.author %}
<div class="btnbox">
  <button id="updatebtn">수정</button>
  <button id="deletebtn">삭제</button>
</div>
{% endif %}
<a href="{% url 'normalboard:index' %}" class="tolist">목록</a>

<div id="updatebox">
  <form action="{% url 'normalboard:edit' post.pk %}" id="updateform" method="POST">
    {% csrf_token %}
    <label for="password">글 비밀번호 </label>
    <input type="password" name="password" id="password">
  </form>
</div>

<div id="deletebox">
  <form action="{% url 'normalboard:delete' post.pk %}" method="POST" id="deleteform">
    {% csrf_token %}
    <label for="password">글 비밀번호 </label>
    <input type="password" name="password" id="password">
  </form>
</div>


{% endblock %}

{% block script %}
<script src="{% static 'detail.js' %}"></script>
<script src="{% static 'highlight.pack.js' %}"></script>
<script>
  hljs.initHighlightingOnLoad();
</script>
{% endblock %}

normalboard/templates/normalboard/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if request.resolver_match.url_name == 'create' %}
<title>일반 게시판 새 글 작성</title>
{% else %}
<title>글 수정 - {{ post.title }}</title>
{% endif %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'form.css' %}">
<link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'martor/css/martor.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}

{% block contents %}

{% if request.resolver_match.url_name == 'create' %}
<h1 class="menutitle">새 글 쓰기</h1>
{% else %}
<h1 class="menutitle">글 수정하기</h1>
{% endif %}


{% if request.resolver_match.url_name == 'create' %}
<form action="" method="POST">
  {% else %}
  <form action="{% url 'normalboard:update' post.pk %}" method="POST">
    {% endif %}
    {% csrf_token %}
    {{ form.as_p }}
    <div class="flex justify-center btnbox">
      <input type="submit" value="등록" class="btn admit">
      {% if request.resolver_match.url_name == 'create' %}
      <a href="{% url 'normalboard:index' %}" class="btn cancel">취소</a>
      {% else %}
      <a href="{% url 'normalboard:detail' post.pk %}" class="btn cancel">취소</a>
      {% endif %}

    </div>
  </form>

  {% endblock %}

  {% block script %}
  <script type="text/javascript" src="{% static 'plugins/js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/typo.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/spellcheck.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'martor/js/martor.min.js' %}"></script>
  {% endblock %}

normalboard/templates/normalboard/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>SSAFY304 일반 게시판</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block contents %}
<div class="boardtitlebox normalboard-titlebox">
  <h1 class="boardtitle">일반 게시판</h1>
</div>

<form action="{% url 'normalboard:create' %}" class="btn-block">
  <button class="btn new-btn"><a href="{% url 'normalboard:create' %}">글쓰기</a></button>
</form>

<div class="boardheader flex-big">
  <div class="boardheader-number block-big element absolute">번호</div>
  <div class="boardheader-title block-big element absolute">제목</div>
  <div class="boardheader-author block-big element absolute">작성자</div>
  <div class="boardheader-date block-big element absolute">작성일</div>
  <div class="boardheader-hit block-big element absolute">조회수</div>
</div>
<hr class="boardline block-big">

{% for post in page_obj %}
<a href="{% url 'normalboard:detail' post.pk %}" class="boardcontent flex-big">
  <div class="boardcontent-number block-big element absolute">{{ post.pk }}</div>
  <div class="boardcontent-title block-big absolute">{{ post.title }} <span
      class="numofcomments inline-big">[{{ post.comment_set.all|length }}]</span> <span class="like"><i
        class="fas fa-heart fa-sm"></i> {{ post.like_users.all|length }}</span></div>
  <div class="boardcontent-author block-big element absolute">{{ post.author.last_name }}{{ post.author.first_name }}
  </div>
  <div class="boardcontent-date block-big element absolute">{{ post.created_at|date:'Y.m.d' }}</div>
  <div class="boardcontent-hit block-big element absolute">{{ post.hit }}</div>
</a>
<hr class="boardline block-big">
{% endfor %}

{% for post in page_obj %}
<a href="{% url 'normalboard:detail' post.pk %}">
  <h3 class="block-small contenttitle">{{ post.title }} <span
      class="numofcomments inline-small">[{{ post.comment_set.all|length }}]</span></h3>
  <div class="postinfo flex-small">
    <div class="post-profile block-small">
      <span class="inline-small postauthor">{{ post.author.last_name }}{{ post.author.first_name }}</span>
      <div class="inline-small seperate"></div>
      <span class="inline-small postdate">{{ post.created_at|date:'y.m.d' }}</span>
    </div>
    <div class="hitbox block-small">
      <img src="{% static 'icon_eye.png' %}" alt="조회수아이콘" class="hiticon-small inline-small">
      <span class="inline-small posthit">{{ post.hit }}</span>
      <span class="like-sm"><i class="fas fa-heart fa-sm"></i></span>
      <span class="inline-small posthit">{{ post.like_users.all|length }}</span>
    </div>
  </div>
</a>
<hr class="block-small">
{% endfor %}

<div class="paginator">
  {% if page_obj.has_previous %}
  <a href="?page=1" class="paginator-item inline-big">처음 <<</a> <a href="?page={{ page_obj.previous_page_number }}"
      class="paginator-item inline-big">이전 <</a> <a href="?page={{ page_obj.previous_page_number }}"
        class="paginator-item inline-small">이전</a>
  {% endif %}
  <span class="current inline-small">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
  <span class="current inline-big">전체 페이지 {{ page_obj.paginator.num_pages }}개 중 {{ page_obj.number }}번째 페이지</span>
  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}" class="paginator-item inline-big">> 다음</a>
  <a href="?page={{ page_obj.next_page_number }}" class="paginator-item inline-small">다음</a>
  <a href="?page={{ page_obj.paginator.num_pages }}" class="paginator-item inline-big">>> 마지막</a>
  {% endif %}
</div>

<form action="{% url 'normalboard:search' %}" class="searchbox">
  <input type="text" name="query" placeholder="글 제목 입력" class="searchinput">
  <button class="searchbtn">검색</button>
</form>
{% endblock %}

normalboard/templates/normalboard/update_post.html
{% extends 'base.html' %}

{% block title %}
<title>일반 게시판 글 수정</title>
{% endblock %}

{% block contents %}
{% if post %}
<form action="/community/update_post/{{ post.pk }}/complete/">
    제목: <input type="text" name="title" id="" value="{{ post.title }}" required>
    내용: <textarea name="content" id="" cols="30" rows="10" required>{{ post.content }}</textarea>
    글 비밀번호: <input type="password" name="password" id="" maxlength="8" required>
    <input type="submit" value="작성완료">
</form>
{% else %}
<form action="/community/update_post/{{ pk }}/complete/">
    제목: <input type="text" name="title" id="" value="{{ title }}" required>
    내용: <textarea name="content" id="" cols="30" rows="10" required>{{ content }}</textarea>
    글 비밀번호: <input type="password" name="password" id="" maxlength="8" required>
    <input type="submit" value="작성완료">
</form>
{% endif %}
{% endblock %}