basic/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.home, name='home'),
    path('meal/', views.meal, name='meal'),
]

codeboard/urls.py
from django.urls import path
from . import views

app_name = 'codeboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.create_comments, name='create_comments'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.delete_comments, name='delete_comments'),
    path('<int:pk>/like/', views.like, name='like'),
]

project304/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic.urls')),
    path('', include('accounts.urls')),
    path('community/', include('normalboard.urls')),
    path('martor/', include('martor.urls')),
    path('code/', include('codeboard.urls')),
    path('question/', include('questionboard.urls')),
]

codeboard/models.py
from django.db import models
from martor.models import MartorField
from django.conf import settings

# Create your models here.

class CodePost(models.Model):
    title = models.CharField(max_length=20)
    password = models.CharField(max_length=8)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = MartorField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hit = models.IntegerField(default=0)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_codeposts')

    def __str__(self):
        return self.title
    
class CodeComment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    codepost = models.ForeignKey(CodePost, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

codeboard/forms.py
from django import forms
from .models import CodePost, CodeComment
from martor.fields import MartorFormField

class CodePostForm(forms.ModelForm):
    title = forms.CharField(
        label='글 제목',
        label_suffix='',
        widget=forms.TextInput(
            attrs = {
                'placeholder':'글 제목을 입력하세요.',
                'class': 'form',
            }
        )
    )
    content = MartorFormField()
    password = forms.CharField(
        label='글 비밀번호 설정',
        label_suffix='',
        widget=forms.PasswordInput(
            attrs = {
                'class': 'form password-form',
            }
        )
    )
    class Meta:
        model = CodePost
        fields = ['title', 'content', 'password']

class CodeCommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
        label_suffix='',
        widget=forms.TextInput(
            attrs = {
                'placeholder': '댓글을 입력하세요.',
                'class': 'commentinput input-responsive',
            }
        )
    )
    class Meta:
        model = CodeComment
        fields = ['content']

codeboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages
from .models import CodePost, CodeComment
from .forms import CodePostForm, CodeCommentForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from datetime import datetime
from django.db.models import F

# Create your views here.
@login_required
def index(request):
    codeposts = CodePost.objects.order_by('-pk')
    paginator = Paginator(codeposts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'codeboard/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = CodePostForm(request.POST)
        if form.is_valid():
            codepost = form.save(commit=False)
            codepost.author = request.user
            codepost.save()
            messages.success(request, '글 작성이 완료되었습니다.')
            return redirect('codeboard:detail', codepost.pk)
        messages.warning(request, '글 제목은 20자 이내, 비밀번호는 8자 이내입니다.')
    else:
        form = CodePostForm()
    context = {
        'form': form,
    }
    return render(request, 'codeboard/form.html', context)

@login_required
def detail(request, pk):
    codepost = get_object_or_404(CodePost, pk=pk)
    codecommentform = CodeCommentForm()
    comments = codepost.codecomment_set.all()
    if request.session.get('_auth_user_id'):
        cookie_name = f'hit:{request.session["_auth_user_id"]}'
    else:
        cookie_name = 'hit'
    tomorrow = datetime.replace(datetime.now(), hour=23, minute=59, second=0)
    expires = datetime.strftime(tomorrow, "%a, %d-%b-%Y %H:%M:%S GMT")
    context = {
        'codepost': codepost,
        'codecommentform': codecommentform,
        'comments': comments,
    }
    response = render(request, 'codeboard/detail.html', context)
    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)
        cookies_list = cookies.split('|')
        if str(codepost.id) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{codepost.id}', expires=expires)
            codepost.hit = F('hit') + 1
            codepost.save()
    else:
        response.set_cookie(cookie_name, codepost.id, expires=expires)
        codepost.hit = F('hit') + 1
        codepost.save()
    return response

@login_required
def edit(request, pk):
    codepost = get_object_or_404(CodePost, pk=pk)
    data = {
        'title': codepost.title,
        'content': codepost.content,
    }
    form = CodePostForm(data)
    context = {
        'form': form,
        'codepost': codepost,
    }
    if request.POST.get('password') != codepost.password:
        messages.error(request, '글 비밀번호가 일치하지 않습니다.')
        return redirect('codeboard:detail', codepost.pk)
    return render(request, 'codeboard/form.html', context)

@login_required
@require_POST
def update(request, pk):
    codepost = get_object_or_404(CodePost, pk=pk)
    data = {
        'title': codepost.title,
        'content': codepost.content,
    }
    if request.method == 'POST':
        form = CodePostForm(request.POST, instance=codepost)
        if form.is_valid():
            if form.cleaned_data.get('password') == codepost.password:
                codepost = form.save()
                messages.success(request, '글 수정이 완료되었습니다.')
                return redirect('codeboard:detail', codepost.pk)
            else:
                messages.error(request, '글 비밀번호가 일치하지 않습니다.')
        else:
            messages.error(request, '제출 양식이 올바르지 않습니다.')
    context = {
        'form': form,
        'codepost': codepost,
    }
    return render(request, 'codeboard/form.html', context)

@login_required
def delete(request, pk): 
    codepost = get_object_or_404(CodePost, pk=pk)
    if request.method == 'POST':
        if request.POST.get('password') == codepost.password:
            codepost.delete()
            messages.success(request, '글 삭제가 완료되었습니다.')
            return redirect('codeboard:index')
        else:
            messages.error(request, '글 비밀번호가 일치하지 않습니다.')
            return redirect('codeboard:detail', codepost.pk)
    context = {
        'codepost': codepost,
    }
    return render(request, 'codeboard/detail.html', context)

@login_required
@require_POST
def create_comments(request, pk):
    codepost = get_object_or_404(CodePost, pk=pk)
    form = CodeCommentForm(request.POST)
    if form.is_valid():
        codecomment = form.save(commit=False)
        codecomment.user = request.user
        codecomment.codepost = codepost
        form.save()
        messages.success(request, '댓글이 등록되었습니다.')
    else:
        messages.error(request, '내용을 입력해 주십시오.')
    return redirect('codeboard:detail', pk)

@login_required
@require_POST
def delete_comments(request, pk, comment_pk):
    codecomment = get_object_or_404(CodeComment, pk=comment_pk)
    codecomment.delete()
    messages.success(request, '댓글이 삭제되었습니다.')
    return redirect('codeboard:detail', pk)

@login_required
def search(request):
    keyword = request.GET.get('query')
    codeposts = CodePost.objects.filter(title__contains=keyword).order_by('-pk')
    paginator = Paginator(codeposts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'codeboard/index.html', context)

@login_required
def like(request, pk):
    codepost = get_object_or_404(CodePost, pk=pk)
    if codepost.like_users.filter(id=request.user.pk).exists():
        codepost.like_users.remove(request.user)
    else:
        codepost.like_users.add(request.user)
    return redirect('codeboard:detail', pk)

codeboard/templates/codeboard/detail.html
{% extends 'base.html' %}
{% load static %}
{% load martortags %}

{% block title %}
<title>{{ codepost.title }} - 코드공유 게시판</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'monokai-sublime.css' %}">
<link rel="stylesheet" href="{% static 'detail.css' %}">
{% endblock %}

{% block contents %}

<h2 class="detailtitle">{{ codepost.title }}</h2>
<div class="postdata">
  <h5 class="authordata">{{ codepost.author.last_name }}{{ codepost.author.first_name }}</h5>
  <div class="seperate"></div>
  <h5 class="datedata">{{ codepost.created_at|date:'Y.m.d H:i' }}</h5>
</div>
<hr>
<div class="content">
  {{ codepost.content|safe_markdown }}
</div>
<hr>

<p class="commentnum-infobox">
  총 <span class="commentnum-info">{{ codepost.codecomment_set.all|length }}</span>건의 댓글이 있습니다.
  {% if request.user in codepost.like_users.all %}
  <a href="{% url 'codeboard:like' codepost.pk %}" class="like"><i class="fas fa-heart"></i>  {{ codepost.like_users.all|length }}</a>
  {% else %}
  <a href="{% url 'codeboard:like' codepost.pk %}" class="like"><i class="far fa-heart"></i>  {{ codepost.like_users.all|length }}</a>
  {% endif %}
</p>
<hr>

<h3 class="comment-write">댓글쓰기</h3>
<form action="{% url 'codeboard:create_comments' codepost.pk %}" method="POST" class="commentform">
  {% csrf_token %}
  {{ codecommentform }}
  <button class="commentbtn btn-responsive comment-create">등록</button>
</form>
<hr>

<div class="comments">
  {% for comment in comments %}
  <div class="commentbox">
    <div class="comment-metadata">
    <div class="comment-profile">
      <span class="comment-username">{{ comment.user.last_name }}{{ comment.user.first_name }}</span>
      <div class="seperate"></div>
      <h5 class="datedata comment-date">{{ comment.created_at|date:'Y.m.d H:i' }}</h5>
    </div>
    {% if comment.user == request.user %}
    <form action="{% url 'codeboard:delete_comments' codepost.pk comment.pk %}" method="POST">
      {% csrf_token %}
      <button class="commentbtn btn-responsive comment-delete">삭제</button>
    </form>
    {% endif %}
  </div>
    <p>{{ comment.content }}</p>
  </div>
  <hr>
  {% endfor %}
</div>





{% if request.user == codepost.author %}
<div class="btnbox">
  <button id="updatebtn">수정</button>
  <button id="deletebtn">삭제</button>
</div>
{% endif %}
<a href="{% url 'codeboard:index' %}" class="tolist">목록</a>

<div id="updatebox">
  <form action="{% url 'codeboard:edit' codepost.pk %}" id="updateform" method="POST">
    {% csrf_token %}
    <label for="password">글 비밀번호 </label>
    <input type="password" name="password" id="password">
  </form>
</div>

<div id="deletebox">
  <form action="{% url 'codeboard:delete' codepost.pk %}" method="POST" id="deleteform">
    {% csrf_token %}
    <label for="password">글 비밀번호 </label>
    <input type="password" name="password" id="password">
  </form>
</div>


{% endblock %}

{% block script %}
<script src="{% static 'detail.js' %}"></script>
<script src="{% static 'highlight.pack.js' %}"></script>
<script>
  hljs.initHighlightingOnLoad();
</script>
{% endblock %}

codeboard/templates/codeboard/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if request.resolver_match.url_name == 'create' %}
<title>코드공유 게시판 새 글 작성</title>
{% else %}
<title>글 수정 - {{ codepost.title }}</title>
{% endif %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'form.css' %}">
<link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'martor/css/martor.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}

{% block contents %}

{% if request.resolver_match.url_name == 'create' %}
<h1 class="menutitle">새 글 쓰기</h1>
{% else %}
<h1 class="menutitle">글 수정하기</h1>
{% endif %}


{% if request.resolver_match.url_name == 'create' %}
<form action="" method="POST">
  {% else %}
  <form action="{% url 'codeboard:update' codepost.pk %}" method="POST">
    {% endif %}
    {% csrf_token %}
    {{ form.as_p }}
    <div class="flex justify-center btnbox">
      <input type="submit" value="등록" class="btn admit">
      {% if request.resolver_match.url_name == 'create' %}
      <a href="{% url 'codeboard:index' %}" class="btn cancel">취소</a>
      {% else %}
      <a href="{% url 'codeboard:detail' codepost.pk %}" class="btn cancel">취소</a>
      {% endif %}

    </div>
  </form>

  {% endblock %}

  {% block script %}
  <script type="text/javascript" src="{% static 'plugins/js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/typo.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/spellcheck.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'martor/js/martor.min.js' %}"></script>
  {% endblock %}

codeboard/templates/codeboard/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>SSAFY304 코드공유 게시판</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock %}

{% block contents %}
<div class="boardtitlebox codeboard-titlebox">
  <h1 class="boardtitle">코드공유 게시판</h1>
</div>
<form action="{% url 'codeboard:create' %}" class="btn-block">
  <button class="btn new-btn"><a href="{% url 'codeboard:create' %}">글쓰기</a></button>
</form>

<div class="boardheader flex-big">
  <div class="boardheader-number block-big element absolute">번호</div>
  <div class="boardheader-title block-big element absolute">제목</div>
  <div class="boardheader-author block-big element absolute">작성자</div>
  <div class="boardheader-date block-big element absolute">작성일</div>
  <div class="boardheader-hit block-big element absolute">조회수</div>
</div>
<hr class="boardline block-big">

{% for codepost in page_obj %}
<a href="{% url 'codeboard:detail' codepost.pk %}" class="boardcontent flex-big">
  <div class="boardcontent-number block-big element absolute">{{ codepost.pk }}</div>
  <div class="boardcontent-title block-big absolute">{{ codepost.title }} <span
      class="numofcomments inline-big">[{{ codepost.codecomment_set.all|length }}]</span>  <span class="like"><i
        class="fas fa-heart fa-sm"></i> {{ codepost.like_users.all|length }}</span></div>
  <div class="boardcontent-author block-big element absolute">{{ codepost.author.last_name }}{{ codepost.author.first_name }}
  </div>
  <div class="boardcontent-date block-big element absolute">{{ codepost.created_at|date:'Y.m.d' }}</div>
  <div class="boardcontent-hit block-big element absolute">{{ codepost.hit }}</div>
</a>
<hr class="boardline block-big">
{% endfor %}

{% for codepost in page_obj %}
<a href="{% url 'codeboard:detail' codepost.pk %}">
  <h3 class="block-small contenttitle">{{ codepost.title }}  <span
      class="numofcomments inline-small">[{{ codepost.codecomment_set.all|length }}]</span></h3>
  <div class="postinfo flex-small">
    <div class="codepost-profile block-small">
      <span class="inline-small postauthor">{{ codepost.author.last_name }}{{ codepost.author.first_name }}</span>
      <div class="inline-small seperate"></div>
      <span class="inline-small postdate">{{ codepost.created_at|date:'y.m.d' }}</span>
    </div>
    <div class="hitbox block-small">
    <img src="{% static 'icon_eye.png' %}" alt="조회수아이콘" class="hiticon-small inline-small">
    <span class="inline-small posthit">{{ codepost.hit }}</span>
    <span class="like-sm"><i class="fas fa-heart fa-sm"></i></span>
    <span class="inline-small posthit">{{ codepost.like_users.all|length }}</span>
  </div>
  </div>
</a>
<hr class="block-small">
{% endfor %}

<div class="paginator">
  {% if page_obj.has_previous %}
  <a href="?page=1" class="paginator-item inline-big">처음 <<</a> <a href="?page={{ page_obj.previous_page_number }}"
      class="paginator-item inline-big">이전 <</a> <a href="?page={{ page_obj.previous_page_number }}"
        class="paginator-item inline-small">이전</a>
  {% endif %}
  <span class="current inline-small">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
  <span class="current inline-big">전체 페이지 {{ page_obj.paginator.num_pages }}개 중 {{ page_obj.number }}번째 페이지</span>
  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}" class="paginator-item inline-big">> 다음</a>
  <a href="?page={{ page_obj.next_page_number }}" class="paginator-item inline-small">다음</a>
  <a href="?page={{ page_obj.paginator.num_pages }}" class="paginator-item inline-big">>> 마지막</a>
  {% endif %}
</div>

<form action="{% url 'codeboard:search' %}" class="searchbox">
  <input type="text" name="query" placeholder="글 제목 입력" class="searchinput">
  <button class="searchbtn">검색</button>
</form>
{% endblock %}